import { templateDetails } from '../types/internalType';

export default [
  {
    name: 'LeadInvite',
    subject: '{{title}} Invite Mail',
    content: `<p>&nbsp;</p><table style="margin: 0 auto; padding: 0; color: #000; background: #FAFAFA; padding-top: 40px; padding-bottom: 40px; font-family: Helvetica;" border="0" width="600px" cellspacing="0" cellpadding="0"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff;"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #4D4948;"><tbody><tr><td height="20">&nbsp;</td></tr><tr><td align="center"><a href="{{site_url}}" target="_blank" rel="noopener">{{title}}</a></td></tr><tr><td height="20">&nbsp;</td></tr></tbody></table></td></tr><tr><td><table style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff; padding: 20px 20px 0;"><tbody><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 0;">Dear <strong>{{lead_name}}</strong>,</td></tr></tbody></table></td></tr><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 20px;">Invite link to your request to proceed: <strong><a href="{{site_url}}{{link}}">click here</a></strong></td></tr></tbody></table></td></tr></tbody></table>`,
  },
  {
    name: 'NewDzitraUser',
    subject: 'Welcome {{title}} User',
    content: `<p>&nbsp;</p><table style="margin: 0 auto; padding: 0; color: #000; background: #FAFAFA; padding-top: 40px; padding-bottom: 40px; font-family: Helvetica;" border="0" width="600px" cellspacing="0" cellpadding="0"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff;"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #4D4948;"><tbody><tr><td height="20">&nbsp;</td></tr><tr><td align="center"><a href="{{site_url}}" target="_blank" rel="noopener">{{title}}</a></td></tr><tr><td height="20">&nbsp;</td></tr></tbody></table></td></tr><tr><td><table style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff; padding: 20px 20px 0;"><tbody><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 0;">Dear <strong>{{name}}</strong>,</td></tr></tbody></table></td></tr><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 20px;">Your login credential is : <strong>{{username}} : {{pass}}</strong></td></tr></tbody></table></td></tr></tbody></table>`,
  },
  {
    name: 'AdminResetForgotPassword',
    subject: 'Reset {{title}} User Forgot Password',
    content: `<p>&nbsp;</p><table style="margin: 0 auto; padding: 0; color: #000; background: #FAFAFA; padding-top: 40px; padding-bottom: 40px; font-family: Helvetica;" border="0" width="600px" cellspacing="0" cellpadding="0"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff;"><tbody><tr><td><table class="full-widths;" style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #4D4948;"><tbody><tr><td height="20">&nbsp;</td></tr><tr><td align="center"><a href="{{site_url}}" target="_blank" rel="noopener">{{title}}</a></td></tr><tr><td height="20">&nbsp;</td></tr></tbody></table></td></tr><tr><td><table style="margin: 0px auto; border-spacing: 0; border-collapse: initial; width: 600px; background: #fff; padding: 20px 20px 0;"><tbody><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 0;">Dear <strong>{{name}}</strong>,</td></tr></tbody></table></td></tr><tr><td style="color: #202020; font-size: 16px; line-height: 150%; text-align: left; padding: 13px 20px;">Link to reset your forgot password : <strong><a href="{{site_url}}{{link}}">click here</a></strong></td></tr></tbody></table></td></tr></tbody></table>`,
  },
] as templateDetails[];
